[colors.primary]
background = "#000000"
foreground = "#BAA997"

[colors.cursor]
text = "#000000"
cursor = "#BAA997"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#BAA997"

[colors.search.matches]
foreground = "#000000"
background = "#BAA997"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#4d4d4d"
background = "#BAA997"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#FF6B6B"
green = "#D6886A"
yellow = "#BAA997"
blue = "#9CFFFA"
magenta = "#D6886A"
cyan = "#9CFFFA"
white = "#BAA997"

[colors.bright]
black = "#4d4d4d"
red = "#ff8888"
green = "#e69d7f"
yellow = "#d4c3b2"
blue = "#b1fffc"
magenta = "#e69d7f"
cyan = "#b1fffc"
white = "#ffffff"

[colors.dim]
black = "#BAA997"
red = "#cc5555"
green = "#a66a54"
yellow = "#9a8879"
blue = "#7dccca"
magenta = "#a66a54"
cyan = "#7dccca"
white = "#4d4d4d"
