# Malifex Theme for Alacritty

[colors.primary]
background = '#000000'
foreground = '#baa997'

[colors.normal]
black   = '#000000'
red     = '#ff6b6b'
green   = '#8b2635'
yellow  = '#baa997'
blue    = '#537a5a'
magenta = '#f2e5bc'
cyan    = '#ff6b6b'
white   = '#f2e5bc'

[colors.bright]
black   = '#4d4d4d'
red     = '#ff8888'
green   = '#a63d4d'
yellow  = '#d4c3b2'
blue    = '#6a9470'
magenta = '#f7eed1'
cyan    = '#ff8888'
white   = '#ffffff'

[colors.cursor]
text = '#000000'
cursor = '#baa997'

[colors.selection]
text = '#baa997'
background = '#1a1a1a'

