[colors.primary]
background = "#000000"
foreground = "#BAA997"

[colors.cursor]
text = "#000000"
cursor = "#BAA997"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#BAA997"

[colors.search.matches]
foreground = "#000000"
background = "#BAA997"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#4d4d4d"
background = "#BAA997"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#499F9A"
green = "#D6886A"
yellow = "#BAA997"
blue = "#FF6B6B"
magenta = "#D6886A"
cyan = "#499F9A"
white = "#BAA997"

[colors.bright]
black = "#4d4d4d"
red = "#6EC9C4"
green = "#e69d7f"
yellow = "#d4c3b2"
blue = "#ff8888"
magenta = "#e69d7f"
cyan = "#6EC9C4"
white = "#ffffff"

[colors.dim]
black = "#BAA997"
red = "#3a7f7b"
green = "#a66a54"
yellow = "#9a8879"
blue = "#cc5555"
magenta = "#a66a54"
cyan = "#3a7f7b"
white = "#4d4d4d"
